### PR TITLE
Rating

### PR DESCRIPTION
**Pull request by chrissearle**
Initial support for devnull feedback/rating

### CODE REVIEW

**Comment by ronnienessa** [comment]
ughh.. Worried about merging my size class changes..

**Comment by chrissearle** [comment]
We might have to push this to apple as early as we can then work on the size class stuff and see if we can get it in in time.

But I'm running out of time - I don't have time to rebase this onto a different master if it's a large change.

**Comment by ronnienessa** [comment]
Looks good to me.. Some changes I would like to make in the UI, but i can do that in adaptive UI branch.

**Comment by chrissearle** [comment]
OK - can I merge?

**Comment by ronnienessa** [comment]
Please merge. I´ll merge my changes soon after. Will disable state restoration on 6+ for some situations.

**Comment by ronnienessa** [comment]
Forgot one thing. We need to make sure that its localized, and some nice accessibility labels would be good as well.

**Pull request merged**
